### ISSUE TITLE
Add ability to add description to albums

### ISSUE THREAD

**Issue by cosmomathieu** [pagestudiocms/cms#56]
Currently the album module only allows you add a title. Consider adding a description field to make it more useful. 

**Tasks**
- [ ] Update schema to support changes 
- [ ] Modify the UI to include a textarea
- [ ] Add ability to insert data into new field and to update
